services:
  app:
    build: .
    image: app:latest
    container_name: flask
    command: /usr/src/app/entrypoint.sh
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
